version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: CODE_DEPLOY
        LoadBalancerInfo:
          ContainerName: gmeet
          ContainerPort: 8080
