version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "python-google-meet" # your ECR repo name (create if not exists)
    AWS_DEFAULT_REGION: "ap-south-1"      # example Mumbai, change to your region
    ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      echo Installing dependencies...
      echo Logging in to Amazon ECR...
      aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  pre_build:
    commands:
      echo Getting Git Commit ID...
      COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      echo Build started on `date`
      echo Building the Docker image...
  build:
    commands:
      docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      echo Pushing the Docker image...
      docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
      echo Writing image definitions file...
      printf '[{"name":"python-google-meet","imageUri":"%s"}]' $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
